application: lp-template
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /common/img
  static_dir: common/img

- url: /common/css
  static_dir: common/css

- url: /common/fonts
  static_dir: common/fonts

- url: /bootstrap/css
  static_dir: bootstrap/css

- url: /bootstrap/js
  static_dir: bootstrap/js

- url: /font-awesome/css
  static_dir: font-awesome/css

- url: /font-awesome/fonts
  static_dir: font-awesome/fonts

- url: /font-awesome/less
  static_dir: font-awesome/less

- url: /font-awesome/scss
  static_dir: font-awesome/scss

- url: /common/js
  static_dir: common/js

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: index.html
  upload: index.html

- url: /
  static_files: form.html
  upload: form.html

# - url: .*
#   script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
